Thank you presenters + resources addition
gurujaya/UPN-VersionGuru pull request #3
Opened 2023-09-08 00:54 UTC by SophiaL9358

The style.css file in Homepage might be a bit wonky because I ctrl c + v'ed together the css generated by the Watch SASS and the file's original css.

2023-09-08 13:57 UTC, InternetRamen requested changes

2023-09-08 13:58 UTC, InternetRamen commented
Everything else looks good! I changed `p-5` to `px-sm-5 py-5` so the buttons don't get cut off on mobile. I think we could delete og.txt and copy.txt. Thank you so much!

2023-09-08 19:49 UTC, SophiaL9358 commented on Homepage/css/copy.txt
Should be deleted now

2023-09-08 19:49 UTC, SophiaL9358 commented on Homepage/css/og.txt
Should be deleted now  x2

2023-09-09 00:21 UTC, InternetRamen approved these changes
LGTM Thanks for submitting! Welcome to the team

2023-09-09 00:22 UTC, merged